spring:
  application:
    name: SmartCityApp

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 16032005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false

swagger-ui:
  path: /swagger-ui/index.html
  disable-swagger-default-url: true

api-docs:
  path: /v3/api-docs

server:
  port: 9595

smartcity-notification:
  url: http://localhost:9596
